### ISSUE TITLE
Follow up on Alpine Packaging 

### ISSUE THREAD

**Issue by sodface** [tari01/odio-edit#2]
Thanks for the changes you made in 22.7.5 to fix the [ppc64le build](https://github.com/tari01/odio-edit/issues/1). I upgraded odio-edit on my aarch64 laptop this morning and on first launch and open of a wav file, odio-edit froze and I had to kill the process. Second launch worked fine. Not sure how to explain that.

Third launch I did from terminal and saw quite a few of the same warnings:

```
(odio-edit:2707): dconf-WARNING **: 07:02:23.171: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)
```

I installed the `dbus-x11` package and now terminal is quiet. The obvious fix is to add that to the package runtime dependency list - do you concur? I don't remember seeing the warning prior to the 22.7.5 update but I could have missed it.

Second observation is that 22.7.5 pulled in a lot of additional packages, presumably due to adding the extra gst-plugins-*. Again, this is not a critique, just feedback on user expectations of what the lightweight part of `A lightweight audio wave editor` might mean in practice.

```
(1/35) Upgrading libcrypto1.1 (1.1.1o-r0 -> 1.1.1p-r0)
(2/35) Upgrading libssl1.1 (1.1.1o-r0 -> 1.1.1p-r0)
(3/35) Upgrading libcurl (7.83.1-r1 -> 7.83.1-r2)
(4/35) Installing openexr (3.1.5-r1)
(5/35) Installing soundtouch (2.3.1-r0)
(6/35) Installing ffmpeg4-libs (4.4.1-r3)
(7/35) Installing chromaprint (1.5.1-r1)
(8/35) Installing libdc1394 (2.2.6-r0)
(9/35) Installing libde265 (1.0.8-r2)
(10/35) Installing tslib (1.22-r0)
(11/35) Installing directfb (1.7.7-r3)
(12/35) Installing faac (1.30-r1)
(13/35) Installing fdk-aac (2.0.2-r0)
(14/35) Installing flite (2.2-r0)
(15/35) Installing portaudio (19.7.0-r0)
(16/35) Installing fluidsynth (2.2.7-r0)
(17/35) Installing gsm (1.0.19-r1)
(18/35) Installing libmodplug (0.8.9.0-r1)
(19/35) Installing neon (0.32.2-r0)
(20/35) Installing libnice (0.1.18-r2)
(21/35) Installing openal-soft (1.22.0-r0)
(22/35) Installing openjpeg (2.5.0-r0)
(23/35) Installing librtmp (2.4_git20190330-r1)
(24/35) Installing sbc (1.5-r0)
(25/35) Installing spandsp (0.0.6-r1)
(26/35) Installing libsrtp (2.4.2-r2)
(27/35) Installing vo-aacenc (0.1.3-r0)
(28/35) Installing vo-amrwbenc (0.1.3-r0)
(29/35) Installing libzbar (0.23.90-r2)
(30/35) Installing gst-plugins-bad (1.20.3-r0)
(31/35) Installing a52dec (0.7.4-r7)
(32/35) Installing opencore-amr (0.1.5-r0)
(33/35) Installing gst-plugins-ugly (1.20.3-r0)
(34/35) Upgrading libodiosacd (22.6.16-r0 -> 22.7.4-r0)
(35/35) Upgrading odio-edit (22.6.15-r0 -> 22.7.5-r0)
```

And finally, on bspwm, on an aarch64 laptop with 11" screen, having odio-edit on half the screen resulted in no GUI way to push `play`. I thought (in previous testing) that the menu included a drop down at the far right top of the toolbar that had entries for un-displayed items but I'm not seeing it now. See screenshot. I may be mis-remembering. Moving the window to full screen fixes it.
![2022-07-05-072414_1366x768_scrot](https://user-images.githubusercontent.com/46695384/177320370-fbb50a25-6d2c-4bf0-a368-6f70c938785d.png)

**Comment by tari01** [comment]
1. The dbus/dbus-x11 issue

Scratch-scratch... I don't have `dbus-x11` intalled, only `dbus`, but no warnings/freezes either. On my end, the `dconf` package satisfies the things needed for an application to use GSettings. On your system it failed to save its things due to something specific to Alpine, I guess. If  `dbus-x11` solves the GSettings/dconf issue, by all means, add it as a dependency.

2. GStreamer dependencies

Erm... Well, yes. No matter what GStreamer pulls in, odio-edit itself is still "light". I'm afraid I don't really have control over this one. On the bright side: on an average Linux desktop, the chances are that all three plugins will be installed at some point, regardless of odio-edit.

3. The toolbar

The window has a minimal size of 640x480. From your screenshot it would seem that bspwm simply cuts off the right side of the window when tiling it. I'm not sure how to act in this matter.

**Comment by sodface** [comment]
Thanks for the responses and testing, sorry if this was an Issue without any real issues. I will add dbus-x11 to the Alpine package dependencies and call it good. Closing.
